#!/bin/sh
tmux new-session -d -s 'data' -n 'Jupyter'
tmux new-window -c ~/Code -n 'code'
tmux new-window -c ~/Code/dotfiles -n 'dotfiles'
tmux new-window -c ~/Code/dotfiles/EC2_dotfiles -n 'EC2_dotfiles'
tmux new-window -c ~/Code/dotfiles/dotfiles_tools_li -n 'dotfiles_tools_li'
tmux new-window -c ~/Code/cortex -n 'cortex'
tmux new-window -c ~/Code/davinci -n 'davinci'
tmux send-keys -t 'data':'code' 'conda update --all --yes' enter
tmux send-keys -t 'data':'EC2_dotfiles' 'git pull' enter
tmux send-keys -t 'data':'dotfiles_tools_li' 'git pull' enter
tmux send-keys -t 'data':'cortex' 'git pull' enter
tmux send-keys -t 'data':'davinci' 'git pull' enter
tmux send-keys -t 'data':'dotfiles' 'stow -v -R -t ~ *' enter
tmux select-window -t 'data':'Jupyter'
tmux attach-session -t 'data'